language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libboost-all-dev
      env:
         - CC=gcc-4.9
         - CXX=g++-4.9

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libboost-all-dev
      env:
         - CC=gcc-5
         - CXX=g++-5

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libboost-all-dev
      env:
        - CC=gcc-6
        - CXX=g++-6

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libboost-all-dev
      env:
        - CC=gcc-7
        - CXX=g++-7

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
            - libboost-all-dev
      env:
        - CC=clang-3.9
        - CXX=clang++-3.9

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - libboost-all-dev
      env:
        - CC=clang-4.0
        - CXX=clang++-4.0"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libboost-all-dev
      env:
        - CC=clang-5.0
        - CXX=clang++-5.0"
addons:
  apt:
    packages:
      - libboost-all-dev
script:
  - cmake .
  - cmake --build .
  - ctest
